### ISSUE TITLE
WebRTC error... "enumerateDevices error"

### ISSUE THREAD

**Issue by interfaith** [webrtcHacks/adapter#304]
Yes, thx ! this new adapter.js does help meteor deal with webrtc  globals. However there are
new problems to replace the old.

TypeError navigator.mediaDevices.getUserMedia is not a function

**Comment by interfaith** [comment]
navigator.mediaDevices.enumerateDevices().then(function(devices) {
					var audioExist = devices.some(function(device) {
						return device.kind === 'audioinput';
					}),

**Comment by interfaith** [comment]
TypeError navigator.mediaDevices.getUserMedia is not a function

**Comment by KaptenJansson** [comment]
Could you please provide some details about the browser, how you are using adapter and which out/ artifact are you using?

**Comment by interfaith** [comment]
My mistake, I was attemping to change
https://github.com/meetecho/janus-gateway to work in meteor.
It is likely that extensive changes are needed to get janus to work in
meteor. I will attempt again and report the result.
Globals in the janus adapter were not copied over.

On Wed, May 18, 2016 at 1:45 AM, Christoffer Jansson <
notifications@github.com> wrote:

> Could you please provide some details about the browser, how you are using
> adapter and which out/ artifact are you using?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/webrtc/adapter/issues/304#issuecomment-219963529>
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
Meteor create janustest.  Then copy the files into janutest/client/lib and
janustest/client/main.js & main.html
for the minimal janus /meteor test. Getting this to work and shown as an
example relative to your site will be of great interest to meteor/janus
developers. Maybe I will stumble on a solution today.


On Wed, May 18, 2016 at 5:31 AM, Mark Spowage <spowage@gmail.com> wrote:

> My mistake, I was attemping to change
> https://github.com/meetecho/janus-gateway to work in meteor.
> It is likely that extensive changes are needed to get janus to work in
> meteor. I will attempt again and report the result.
> Globals in the janus adapter were not copied over.
>
> On Wed, May 18, 2016 at 1:45 AM, Christoffer Jansson <
> notifications@github.com> wrote:
>
>> Could you please provide some details about the browser, how you are
>> using adapter and which out/ artifact are you using?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/webrtc/adapter/issues/304#issuecomment-219963529>
>>
>
>
>
> --
> -----
> Fight back spam! Download the Blue Frog.
> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by KaptenJansson** [comment]
Sorry I still do not get it. I'm not familiar with meteor or janus (it's better not to assume people know anything about what you are trying to do).

In the future please include step by step of what you have done, a code snippet on how you include adapter, which version of adapter and the browser used etc.

Thanks!

**Comment by interfaith** [comment]
surprise! , a fresh attempt did work with your adapter.js.  now i can post
a working example of janus/meteor thankyou !

this addition did not work though ?


var webrtcDetectedBrowser = null;
var webrtcDetectedVersion = null;
var webrtcMinimumVersion = null;

 module.exports = {

    webrtcDetectedBrowser: webrtcDetectedBrowser,
    webrtcDetectedVersion: webrtcDetectedVersion,
    webrtcMinimumVersion: webrtcMinimumVersion,


  };

i wonder how does this header code get derived ? some build process??
(function(f){if(typeof exports==="object"&&typeof
module!=="undefined"){module.exports=f()}else if(typeof
define==="function"&&define.amd){define([],f)}else{var g;if(typeof
window!=="undefined"){g=window}else if(typeof
global!=="undefined"){g=global}else if(typeof
self!=="undefined"){g=self}else{g=this}g.adapter = f()}})(function(){var
define,module,exports;return (function e(t,n,r){function
s(o,u){if(!n[o]){if(!t[o]){var a=typeof
require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return
i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw
f.code="MODULE_NOT_FOUND",f}var
l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var
n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var
i=typeof require=="function"&&require;for(var
o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
 /* eslint-env node */



On Wed, May 18, 2016 at 5:58 AM, Christoffer Jansson <
notifications@github.com> wrote:

> Closed #304 <https://github.com/webrtc/adapter/issues/304>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/webrtc/adapter/issues/304#event-664355910>
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
A new attempt did work with Meteor 1.3 and Janus which had added globals.
