### ISSUE TITLE
test: firefox fails due to lack of removeStream

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#472]
```
# dtmf
ok 103 Page loaded
not ok 104 PeerConnection failure: TypeError: pc1.removeStream is not a function
  ---
    operator: fail
    at: seleniumHelpers.loadTestPage.then.then (/home/fippo/webrtc/adapter/test/test.js:1539:11)
  ...
```
@jan-ivar can you take a look? Saw this when running tests locally with FF52... which doesn't have removeStream so the test is bad probably

**Comment by jan-ivar** [comment]
Whoops, my bad. Tried [too hard to make the test work with Chrome](https://github.com/webrtc/adapter/commit/51d0a52190d579076e678bd70675f4ec9a2939dd).
